name: YouTube Follower Scraper

on:
  schedule:
    - cron: '0 0 * * 1'  # Runs at 00:00 UTC Monday (8:00 AM SGT Monday)
  workflow_dispatch:  # Allows manual triggering

jobs:
  scrape:
    runs-on: windows-latest
    
    steps:
    - uses: actions/checkout@v3
    
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.12'
        
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        
    - name: Set up Chrome
      uses: browser-actions/setup-chrome@latest
      
    - name: Run YouTube scraper
      env:
        AIRTABLE_PAT: ${{ secrets.AIRTABLE_PAT }}
        AIRTABLE_BASE_ID: ${{ secrets.AIRTABLE_BASE_ID }}
        AIRTABLE_TABLE_NAME: ${{ secrets.AIRTABLE_TABLE_NAME }}
      run: |
        python youtube_follower_scraper.py
